# This is not actually being used, just set up to get pickle working properly
base: &base
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['USER'] %>
  pool: 5

development:
  database: lean_crm_development
  <<: *base

test:
  database: lean_crm_test
  <<: *base

cucumber:
  database: lean_crm_cucumber
  <<: *base

production:
  database: lean_crm_production
  <<: *base
