development: &global_settings
  adapter: mongodb
  database: salesflip_development
  host: 127.0.0.1
  port: 27017
  username:
  password:

test:
  <<: *global_settings
  database: salesflip_test

cucumber:
  <<: *global_settings
  database: salesflip_cucumber

production:
  <<: *global_settings
  host: 178.63.20.76
  username: site
  password: bu5g3r
  database: salesflip_production
