base: &base
  adapter: mongodb
  database: coolapp
  #host: genesis.mongohq.com
  #username: your-username
  #password: your-password

development:
  <<: *base
  database: lean_crm_development

test:
  <<: *base
  database: lean_crm_test

cucumber:
  <<: *base
  database: lean_crm_cucumber

production:
  <<: *base
  database: lean_crm_production
