base: &base
  adapter: mongodb
  #host: genesis.mongohq.com
  #username: your-username
  #password: your-password

development:
  <<: *base
  database: salesflip_development

test:
  <<: *base
  database: salesflip_test

cucumber:
  <<: *base
  database: salesflip_cucumber

production:
  <<: *base
  database: salesflip_production
